# Generated by Django 3.1.5 on 2021-02-13 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_products_preparationtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='uploades/SpecialItems/')),
                ('active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.categories')),
                ('item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.products')),
            ],
        ),
    ]
