# Generated by Django 3.1.5 on 2021-02-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210213_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialitems',
            name='Active',
            field=models.BooleanField(default=False, help_text='Active'),
        ),
    ]
