# Generated by Django 3.1.5 on 2021-02-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210213_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialitems',
            name='Active',
        ),
        migrations.AddField(
            model_name='specialitems',
            name='Active_InActive_SpecialItem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialitems',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='specialitems',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
